language: ruby
gemfile:
- gemfiles/travis.gemfile
rvm:
- 1.9.3
env:
  global:
  - secure: RgkauPEqNogtHal3Uv7RN/NuVmIUV3zkMQ0IZRXPaStkCICMyHhLN/MYHOvSA30LWff0t8A3hwRJ4YMUfUY/LZqa8eSOk7GVIxo8/BieMYQxrjGul2WzOnshgaO9gqpEuNzoMrHn7SqZ+ZrzvaqSg2ahGHz47JqK8VICwwOWJBc=
  - secure: R2QzemamiK9XVEEz70uX36g2j5dfimYqoCy0Jwu4fqpLCCJDiwziQ+jKZUP1mi8b7yVHZpWqZFrj+Qj1f1EKbhozo3LVqvMdCICECJz/urie8WsFwtINR3qDBiyFxPk4gh0mO7f9cEbdD9h9Ud4+YUSX2uJB0A4NiTeqtCZ9SIQ=
  - secure: XQLzeKvSO3GB40VHWz1Ulobnp8ZRKA5Z2xmn99V7YvHpyuQiqN+3Iaj+UOEq+eb/6Lunv89UDsLNbSRggrk9LADdY+y4rQMeLsrYUo8CR+bvZ20VIhEuiTHhGYtHQhLY7qeZT8ovdQRdRhNf0Xuqt6WqYSGGqhdyyudYStJD0nE=
  matrix:
  - KITCHEN_INSTANCE='default-ubuntu-1204'
  - KITCHEN_INSTANCE='default-ubuntu-1004'
  - KITCHEN_INSTANCE='default-centos-64'
  - KITCHEN_INSTANCE='default-centos-53'
  - KITCHEN_INSTANCE='add-servers-ubuntu-1204'
  - KITCHEN_INSTANCE='add-servers-ubuntu-1004'
  - KITCHEN_INSTANCE='add-servers-centos-64'
  - KITCHEN_INSTANCE='add-servers-centos-53'
  - KITCHEN_INSTANCE='del-servers-ubuntu-1204'
  - KITCHEN_INSTANCE='del-servers-ubuntu-1004'
  - KITCHEN_INSTANCE='del-servers-centos-64'
  - KITCHEN_INSTANCE='del-servers-centos-53'
script:
- bundle exec foodcritic ./ -f 'any'
- bundle exec kitchen test $KITCHEN_INSTANCE
after_script:
- bundle exec kitchen destroy $KITCHEN_INSTANCE
notifications:
  email:
  - abutovich@qubell.com
